### ISSUE TITLE
Grunt-run doesn't work with lodash 4.2: undefined is not a function

### ISSUE THREAD

**Issue by asinyagin** [spalger/grunt-run#22]
Hi,

That's not a bug, just FYI. Grunt-run with lodash 4.2.0 gives an error `undefined is not a function`.

There're big amount of breaking changes in the new lodash. For example they've replaced `_.contains` with `_.includes`, so grunt-run fails here: https://github.com/spalger/grunt-run/blob/master/tasks/run.js#L74
